name: Feature request
description: Suggest a new idea or enhancement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Proposals with a concrete use case are easier to prioritize.
  - type: input
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I need to cluster text by language before running kmeans
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe what you want to happen
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: extra
    attributes:
      label: Additional context
